import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface InvoiceData {
  invoiceNumber: string;
  issueDate: string;
  dueDate: string;
  sellerName: string;
  sellerGSTIN: string;
  buyerName: string;
  buyerGSTIN: string;
  items: Array<{
    description: string;
    quantity: number;
    rate: number;
    amount: number;
  }>;
  amount: number;
  gstAmount: number;
  totalAmount: number;
  ipfsHash?: string;
  sha256Hash?: string;
  blockchainTxHash?: string;
}

export const generateInvoicePDF = (invoice: InvoiceData) => {
  const doc = new jsPDF();
  
  // Header
  doc.setFillColor(0, 212, 255);
  doc.rect(0, 0, 210, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('TAX INVOICE', 105, 20, { align: 'center' });
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('Blockchain-Verified Invoice', 105, 28, { align: 'center' });
  doc.text('Powered by ChainVoice', 105, 34, { align: 'center' });
  
  // Reset text color
  doc.setTextColor(0, 0, 0);
  
  // Invoice Details Box
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text(`Invoice #: ${invoice.invoiceNumber}`, 14, 50);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Issue Date: ${new Date(invoice.issueDate).toLocaleDateString('en-IN')}`, 14, 57);
  doc.text(`Due Date: ${new Date(invoice.dueDate).toLocaleDateString('en-IN')}`, 14, 63);
  
  // Seller Details
  doc.setFillColor(240, 240, 240);
  doc.rect(14, 75, 90, 35, 'F');
  doc.setFont('helvetica', 'bold');
  doc.text('SELLER DETAILS', 16, 82);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.text(invoice.sellerName, 16, 89);
  doc.text(`GSTIN: ${invoice.sellerGSTIN}`, 16, 95);
  doc.text('Address: [Seller Address]', 16, 101);
  doc.text('Contact: [Seller Contact]', 16, 107);
  
  // Buyer Details
  doc.rect(106, 75, 90, 35, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.text('BUYER DETAILS', 108, 82);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.text(invoice.buyerName, 108, 89);
  doc.text(`GSTIN: ${invoice.buyerGSTIN}`, 108, 95);
  doc.text('Address: [Buyer Address]', 108, 101);
  doc.text('Contact: [Buyer Contact]', 108, 107);
  
  // Items Table
  autoTable(doc, {
    startY: 120,
    head: [['Description', 'Qty', 'Rate (₹)', 'Amount (₹)']],
    body: invoice.items.map(item => [
      item.description,
      item.quantity.toString(),
      item.rate.toLocaleString('en-IN'),
      item.amount.toLocaleString('en-IN')
    ]),
    theme: 'grid',
    headStyles: { fillColor: [0, 212, 255], textColor: [255, 255, 255] },
    styles: { fontSize: 9 },
  });
  
  // @ts-ignore - autoTable adds finalY property
  const finalY = doc.lastAutoTable.finalY || 120;
  
  // Totals
  const totalsY = finalY + 10;
  doc.setFontSize(10);
  
  doc.text('Subtotal:', 140, totalsY);
  doc.text(`₹${invoice.amount.toLocaleString('en-IN')}`, 180, totalsY, { align: 'right' });
  
  doc.text('GST (18%):', 140, totalsY + 7);
  doc.text(`₹${invoice.gstAmount.toLocaleString('en-IN')}`, 180, totalsY + 7, { align: 'right' });
  
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('Total Amount:', 140, totalsY + 15);
  doc.text(`₹${invoice.totalAmount.toLocaleString('en-IN')}`, 180, totalsY + 15, { align: 'right' });
  
  // Blockchain Verification Section
  const blockchainY = totalsY + 30;
  doc.setFillColor(230, 255, 230);
  doc.rect(14, blockchainY, 182, 40, 'F');
  
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 150, 0);
  doc.text('✓ BLOCKCHAIN VERIFIED', 16, blockchainY + 8);
  
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(0, 0, 0);
  
  if (invoice.ipfsHash) {
    doc.text(`IPFS CID: ${invoice.ipfsHash.substring(0, 50)}...`, 16, blockchainY + 15);
  }
  
  if (invoice.sha256Hash) {
    doc.text(`SHA-256 Hash: ${invoice.sha256Hash}`, 16, blockchainY + 21);
  }
  
  if (invoice.blockchainTxHash) {
    doc.text(`Blockchain Tx: ${invoice.blockchainTxHash}`, 16, blockchainY + 27);
  }
  
  doc.setFontSize(7);
  doc.setTextColor(100, 100, 100);
  doc.text('This invoice is cryptographically secured and registered on Hyperledger Fabric blockchain.', 16, blockchainY + 34);
  doc.text('Any tampering will be instantly detected through hash verification.', 16, blockchainY + 38);
  
  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text('Generated by ChainVoice - Blockchain Invoice Financing Platform', 105, 285, { align: 'center' });
  doc.text(`Generated on: ${new Date().toLocaleString('en-IN')}`, 105, 290, { align: 'center' });
  
  return doc;
};

export const downloadInvoicePDF = (invoice: InvoiceData) => {
  const doc = generateInvoicePDF(invoice);
  doc.save(`Invoice_${invoice.invoiceNumber}.pdf`);
};

export const generateHashVerificationCertificate = (data: {
  invoiceNumber: string;
  sellerName: string;
  buyerName: string;
  amount: number;
  uploadedHash: string;
  onChainHash: string;
  isMatch: boolean;
  verifiedBy: string;
  verificationDate: string;
}) => {
  const doc = new jsPDF();
  
  // Header
  if (data.isMatch) {
    doc.setFillColor(16, 185, 129);
  } else {
    doc.setFillColor(239, 68, 68);
  }
  doc.rect(0, 0, 210, 50, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(28);
  doc.setFont('helvetica', 'bold');
  doc.text('HASH VERIFICATION', 105, 25, { align: 'center' });
  doc.text(data.isMatch ? 'CERTIFICATE' : 'REPORT', 105, 38, { align: 'center' });
  
  // Status Badge
  doc.setFontSize(16);
  if (data.isMatch) {
    doc.text('✓ VERIFIED', 105, 60, { align: 'center' });
    doc.setTextColor(16, 185, 129);
  } else {
    doc.text('✗ MISMATCH DETECTED', 105, 60, { align: 'center' });
    doc.setTextColor(239, 68, 68);
  }
  
  // Invoice Details
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Invoice Details', 14, 80);
  
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(`Invoice Number: ${data.invoiceNumber}`, 14, 90);
  doc.text(`Seller: ${data.sellerName}`, 14, 97);
  doc.text(`Buyer: ${data.buyerName}`, 14, 104);
  doc.text(`Amount: ₹${data.amount.toLocaleString('en-IN')}`, 14, 111);
  
  // Hash Comparison
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('Hash Comparison', 14, 130);
  
  doc.setFillColor(240, 240, 240);
  doc.rect(14, 135, 182, 25, 'F');
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.text('On-Chain Hash (Hyperledger Fabric):', 16, 142);
  doc.setFont('courier', 'normal');
  doc.setFontSize(8);
  doc.text(data.onChainHash, 16, 149);
  doc.text(data.onChainHash.substring(40), 16, 154);
  
  doc.rect(14, 165, 182, 25, 'F');
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.text('Uploaded Document Hash:', 16, 172);
  doc.setFont('courier', 'normal');
  doc.setFontSize(8);
  doc.text(data.uploadedHash, 16, 179);
  doc.text(data.uploadedHash.substring(40), 16, 184);
  
  // Verification Result
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Verification Result', 14, 205);
  
  if (data.isMatch) {
    doc.setFillColor(230, 255, 230);
    doc.rect(14, 210, 182, 40, 'F');
    doc.setTextColor(0, 150, 0);
    doc.setFontSize(14);
    doc.text('✓ HASH MATCH CONFIRMED', 105, 222, { align: 'center' });
    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    doc.text('The uploaded document matches the blockchain record exactly.', 105, 232, { align: 'center' });
    doc.text('No tampering detected. Document integrity confirmed.', 105, 239, { align: 'center' });
    doc.text('This invoice is eligible for financing.', 105, 246, { align: 'center' });
  } else {
    doc.setFillColor(255, 230, 230);
    doc.rect(14, 210, 182, 40, 'F');
    doc.setTextColor(200, 0, 0);
    doc.setFontSize(14);
    doc.text('✗ HASH MISMATCH DETECTED', 105, 222, { align: 'center' });
    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    doc.text('The uploaded document does NOT match the blockchain record.', 105, 232, { align: 'center' });
    doc.text('Document may have been altered after registration.', 105, 239, { align: 'center' });
    doc.text('DO NOT PROCEED with financing. Flag for investigation.', 105, 246, { align: 'center' });
  }
  
  // Verification Details
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Verified By: ${data.verifiedBy}`, 14, 265);
  doc.text(`Verification Date: ${data.verificationDate}`, 14, 272);
  doc.text('Verification Method: SHA-256 Hash Comparison', 14, 279);
  
  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text('ChainVoice - Blockchain Invoice Financing Platform', 105, 290, { align: 'center' });
  
  return doc;
};

export const downloadHashVerificationCertificate = (data: Parameters<typeof generateHashVerificationCertificate>[0]) => {
  const doc = generateHashVerificationCertificate(data);
  const status = data.isMatch ? 'Verified' : 'Mismatch';
  doc.save(`Hash_Verification_${status}_${data.invoiceNumber}.pdf`);
};
